services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/dojosolutions
    depends_on:
      - mongo
    ports:
      - '3000:3000'

  mongo:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:v3.7.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    depends_on:
      - app

  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  mongo_data:
