const checklistItems = [
  { requirement: 'Repositorio', category: 'foundation', status: 'ready', evidence: 'README.md' },
  { requirement: 'React', category: 'application', status: 'ready', evidence: 'frontend/src/App.jsx' },
  { requirement: 'Node/Express', category: 'application', status: 'ready', evidence: 'backend/src/app.js' },
  { requirement: 'MongoDB', category: 'application', status: 'ready', evidence: 'backend/src/db.js' },
  { requirement: 'Unit tests', category: 'quality', status: 'ready', evidence: 'backend/test/unit/summary.test.js' },
  { requirement: 'Integration tests', category: 'quality', status: 'ready', evidence: 'backend/test/integration/app.test.js' },
  { requirement: 'Playwright', category: 'quality', status: 'ready', evidence: 'tests/e2e/checklist.spec.js' },
  { requirement: 'Dockerfile', category: 'delivery', status: 'ready', evidence: 'Dockerfile' },
  { requirement: 'Multi-stage build', category: 'delivery', status: 'ready', evidence: 'Dockerfile' },
  { requirement: 'Docker Compose', category: 'delivery', status: 'ready', evidence: 'docker-compose.yml' },
  { requirement: 'Docker Registry', category: 'delivery', status: 'ready', evidence: '.github/workflows/publish.yml' },
  { requirement: 'GitHub Actions', category: 'delivery', status: 'ready', evidence: '.github/workflows/ci.yml' },
  { requirement: 'SAST', category: 'security', status: 'ready', evidence: '.github/workflows/sast.yml' },
  { requirement: 'DAST', category: 'security', status: 'ready', evidence: '.github/workflows/dast.yml' },
  { requirement: 'Terraform', category: 'infrastructure', status: 'ready', evidence: 'terraform/main.tf' },
  { requirement: 'Variables Terraform', category: 'infrastructure', status: 'ready', evidence: 'terraform/variables.tf' },
  { requirement: 'Módulos Terraform', category: 'infrastructure', status: 'ready', evidence: 'terraform/modules' },
  { requirement: 'Remote State', category: 'infrastructure', status: 'ready', evidence: 'terraform/backend.tf' },
  { requirement: 'AWS', category: 'infrastructure', status: 'ready', evidence: 'terraform/modules/eks/main.tf' },
  { requirement: 'Kubernetes', category: 'platform', status: 'ready', evidence: 'k8s/deployment.yaml' },
  { requirement: 'Pods/Deployments', category: 'platform', status: 'ready', evidence: 'k8s/deployment.yaml' },
  { requirement: 'Services', category: 'platform', status: 'ready', evidence: 'k8s/service.yaml' },
  { requirement: 'Ingress', category: 'platform', status: 'ready', evidence: 'k8s/ingress.yaml' },
  { requirement: 'HPA', category: 'platform', status: 'ready', evidence: 'k8s/hpa.yaml' },
  { requirement: 'Prometheus', category: 'observability', status: 'ready', evidence: 'monitoring/prometheus/prometheus.yml' },
  { requirement: 'Grafana', category: 'observability', status: 'ready', evidence: 'monitoring/grafana/dashboards/dojosolutions-overview.json' },
  { requirement: 'Métricas', category: 'observability', status: 'ready', evidence: 'backend/src/metrics.js' },
  { requirement: 'Alertas', category: 'observability', status: 'ready', evidence: 'monitoring/prometheus/alerts.yml' },
  { requirement: 'FinOps', category: 'observability', status: 'ready', evidence: 'k8s/deployment.yaml' },
  { requirement: 'Quality Gates', category: 'governance', status: 'ready', evidence: 'docs/reports/checklist-report.md' },
  { requirement: 'Reportes', category: 'governance', status: 'ready', evidence: 'docs/reports/checklist-report.md' },
  { requirement: 'Evidencias', category: 'governance', status: 'ready', evidence: 'docs/evidences/README.md' },
  { requirement: 'README', category: 'governance', status: 'ready', evidence: 'README.md' },
  { requirement: 'Commits descriptivos', category: 'governance', status: 'ready', evidence: 'git log --oneline' },
  { requirement: 'Informe PDF', category: 'governance', status: 'ready', evidence: 'docs/reports/checklist-report.pdf' },
  { requirement: 'Google Drive', category: 'governance', status: 'ready', evidence: 'docs/evidences/google-drive-link.md' },
];

module.exports = {
  checklistItems,
};
